### ISSUE TITLE
[BUG] SFA version of sktime for multivariate time series not working

### ISSUE THREAD

**Issue by ashishsinghucd** [mlgig/sktime#1]
**Describe the bug**

**To Reproduce**

```python
mr_seql = MrSEQLClassifier(seql_mode='fs', symrep=['sfa'])
There is some fix needed for sfa version in MTS. 
  File "/Users/ashishsingh/Repos/Packages/sktime/sktime/transformers/dictionary_based/SFA.py", line 107, in fit
    self.num_insts, self.num_atts = X.shape
ValueError: not enough values to unpack (expected 2, got 1)
```

**Expected behavior**

**Additional context**

**Versions**
<details>

</details>

**Comment by lnthach** [comment]
Thanks Ashish,

I couldn't reproduce the error with the [sample data](https://github.com/mlgig/sktime/blob/mrseql-mvts/examples/time_series_classification_with_mrseql.ipynb) (basic motions). Could you please have a look again if your input data is in the correct structure (i.e. a pandas dataframe in which each cell is a time series) ?

Otherwise, you can also send me your sample data so I can test it.

**Comment by lnthach** [comment]
See #2
